extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
  memory_ballast:
    size_mib: 512

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:  

  logging:
    verbosity: detailed
   
  prometheus:
    endpoint: "0.0.0.0:9023"    
    resource_to_telemetry_conversion:
      enabled: true
  
  elasticsearch/trace:
    endpoints: ["http://middleware-elastic:9200"]
    traces_index: masa-stack-traces-0.6.1
  elasticsearch/log:  
    endpoints: ["http://middleware-elastic:9200"]
    logs_index: masa-stack-logs-0.6.1  

service:

  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/log]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/trace]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

  extensions: [health_check, pprof, zpages,memory_ballast]